# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"7\n\x10VectorClockEntry\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\"x\n\x11PlaceOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.order.OrderItem\x12-\n\x0cvector_clock\x18\x03 \x03(\x0b\x32\x17.order.VectorClockEntry\"E\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nunit_price\x18\x03 \x01(\x01\"{\n\x12PlaceOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x12-\n\x0cvector_clock\x18\x04 \x03(\x0b\x32\x17.order.VectorClockEntry\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"s\n\x10GetOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x01\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"6\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"7\n\x13\x43\x61ncelOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd4\x01\n\x0cOrderService\x12\x41\n\nPlaceOrder\x12\x18.order.PlaceOrderRequest\x1a\x19.order.PlaceOrderResponse\x12;\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12\x44\n\x0b\x43\x61ncelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCKENTRY']._serialized_start=22
  _globals['_VECTORCLOCKENTRY']._serialized_end=77
  _globals['_PLACEORDERREQUEST']._serialized_start=79
  _globals['_PLACEORDERREQUEST']._serialized_end=199
  _globals['_ORDERITEM']._serialized_start=201
  _globals['_ORDERITEM']._serialized_end=270
  _globals['_PLACEORDERRESPONSE']._serialized_start=272
  _globals['_PLACEORDERRESPONSE']._serialized_end=395
  _globals['_GETORDERREQUEST']._serialized_start=397
  _globals['_GETORDERREQUEST']._serialized_end=432
  _globals['_GETORDERRESPONSE']._serialized_start=434
  _globals['_GETORDERRESPONSE']._serialized_end=549
  _globals['_CANCELORDERREQUEST']._serialized_start=551
  _globals['_CANCELORDERREQUEST']._serialized_end=605
  _globals['_CANCELORDERRESPONSE']._serialized_start=607
  _globals['_CANCELORDERRESPONSE']._serialized_end=662
  _globals['_ORDERSERVICE']._serialized_start=665
  _globals['_ORDERSERVICE']._serialized_end=877
# @@protoc_insertion_point(module_scope)
