# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"7\n\x10VectorClockEntry\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\"x\n\x0e\x43omputeRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12/\n\x0cvector_clock\x18\x04 \x03(\x0b\x32\x19.payment.VectorClockEntry\"{\n\x0f\x43omputeResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12/\n\x0cvector_clock\x18\x04 \x03(\x0b\x32\x19.payment.VectorClockEntry\"\x1e\n\x0c\x43rashRequest\x12\x0e\n\x06reason\x18\x01 \x01(\t\",\n\rCrashResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x10\n\x0eRecoverRequest\".\n\x0fRecoverResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xff\x01\n\x0ePaymentService\x12<\n\x07\x43ompute\x12\x17.payment.ComputeRequest\x1a\x18.payment.ComputeResponse\x12\x36\n\x05\x43rash\x12\x15.payment.CrashRequest\x1a\x16.payment.CrashResponse\x12<\n\x07Recover\x12\x17.payment.RecoverRequest\x1a\x18.payment.RecoverResponse\x12\x39\n\x06Health\x12\x16.payment.HealthRequest\x1a\x17.payment.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCKENTRY']._serialized_start=26
  _globals['_VECTORCLOCKENTRY']._serialized_end=81
  _globals['_COMPUTEREQUEST']._serialized_start=83
  _globals['_COMPUTEREQUEST']._serialized_end=203
  _globals['_COMPUTERESPONSE']._serialized_start=205
  _globals['_COMPUTERESPONSE']._serialized_end=328
  _globals['_CRASHREQUEST']._serialized_start=330
  _globals['_CRASHREQUEST']._serialized_end=360
  _globals['_CRASHRESPONSE']._serialized_start=362
  _globals['_CRASHRESPONSE']._serialized_end=406
  _globals['_RECOVERREQUEST']._serialized_start=408
  _globals['_RECOVERREQUEST']._serialized_end=424
  _globals['_RECOVERRESPONSE']._serialized_start=426
  _globals['_RECOVERRESPONSE']._serialized_end=472
  _globals['_HEALTHREQUEST']._serialized_start=474
  _globals['_HEALTHREQUEST']._serialized_end=489
  _globals['_HEALTHRESPONSE']._serialized_start=491
  _globals['_HEALTHRESPONSE']._serialized_end=523
  _globals['_PAYMENTSERVICE']._serialized_start=526
  _globals['_PAYMENTSERVICE']._serialized_end=781
# @@protoc_insertion_point(module_scope)
