# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"7\n\x10VectorClockEntry\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\"l\n\x11\x43heckStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x31\n\x0cvector_clock\x18\x03 \x03(\x0b\x32\x1b.inventory.VectorClockEntry\"o\n\x12\x43heckStockResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x13\n\x0bstock_level\x18\x02 \x01(\x05\x12\x31\n\x0cvector_clock\x18\x03 \x03(\x0b\x32\x1b.inventory.VectorClockEntry\"\x80\x01\n\x13ReserveStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x31\n\x0cvector_clock\x18\x04 \x03(\x0b\x32\x1b.inventory.VectorClockEntry\"\x83\x01\n\x14ReserveStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x31\n\x0cvector_clock\x18\x04 \x03(\x0b\x32\x1b.inventory.VectorClockEntry\"=\n\x13ReleaseStockRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"8\n\x14ReleaseStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x02\n\x10InventoryService\x12I\n\nCheckStock\x12\x1c.inventory.CheckStockRequest\x1a\x1d.inventory.CheckStockResponse\x12O\n\x0cReserveStock\x12\x1e.inventory.ReserveStockRequest\x1a\x1f.inventory.ReserveStockResponse\x12O\n\x0cReleaseStock\x12\x1e.inventory.ReleaseStockRequest\x1a\x1f.inventory.ReleaseStockResponse\x12=\n\x06Health\x12\x18.inventory.HealthRequest\x1a\x19.inventory.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCKENTRY']._serialized_start=30
  _globals['_VECTORCLOCKENTRY']._serialized_end=85
  _globals['_CHECKSTOCKREQUEST']._serialized_start=87
  _globals['_CHECKSTOCKREQUEST']._serialized_end=195
  _globals['_CHECKSTOCKRESPONSE']._serialized_start=197
  _globals['_CHECKSTOCKRESPONSE']._serialized_end=308
  _globals['_RESERVESTOCKREQUEST']._serialized_start=311
  _globals['_RESERVESTOCKREQUEST']._serialized_end=439
  _globals['_RESERVESTOCKRESPONSE']._serialized_start=442
  _globals['_RESERVESTOCKRESPONSE']._serialized_end=573
  _globals['_RELEASESTOCKREQUEST']._serialized_start=575
  _globals['_RELEASESTOCKREQUEST']._serialized_end=636
  _globals['_RELEASESTOCKRESPONSE']._serialized_start=638
  _globals['_RELEASESTOCKRESPONSE']._serialized_end=694
  _globals['_HEALTHREQUEST']._serialized_start=696
  _globals['_HEALTHREQUEST']._serialized_end=711
  _globals['_HEALTHRESPONSE']._serialized_start=713
  _globals['_HEALTHRESPONSE']._serialized_end=745
  _globals['_INVENTORYSERVICE']._serialized_start=748
  _globals['_INVENTORYSERVICE']._serialized_end=1066
# @@protoc_insertion_point(module_scope)
